### PR TITLE
jeffrey0Feature/je 14 pobranie pojedynczego maila

### PR DESCRIPTION
**Pull request by dzefrej0**
Please take a look.

### CODE REVIEW

**Comment by Cinek1812** [comment]
It looks quite nice :)
Have you checked that the content regexp work correctly ?

**Comment by dzefrej0** [comment]
I just can`t see where is the content in this file testlist.mbox

**Comment by dzefrej0** [comment]
I will do it really quick if some1 tell me where is content in this :)

**Comment by Cinek1812** [comment]
The content is at the end of the correct email, i mean in testlist.mbox it will be just "test" etc... :)
For example:
(...)
List-Help: <mailto:testlist-request@lists.malcolmhardie.com?subject=help>
List-Post: <mailto:testlist@lists.malcolmhardie.com>
List-Subscribe: <http://lists.malcolmhardie.com/cgi-bin/mailman/listinfo/testlist>,
	<mailto:testlist-request@lists.malcolmhardie.com?subject=subscribe>
List-Id: <testlist.lists.malcolmhardie.com>
List-Unsubscribe: <http://lists.malcolmhardie.com/cgi-bin/mailman/listinfo/testlist>,
	<mailto:testlist-request@lists.malcolmhardie.com?subject=unsubscribe>
List-Archive: <http://lists.malcolmhardie.com/pipermail/testlist/>

**# test**  <---- content :)



From Angus.Hardie@malcolmhardie.com Sun Apr 18 02:35:33 2004
Received: from pol.malcolmhardie.com ([213.152.32.218] helo=malcolmhardie.com)
	by marilac.malcolmhardie.com with asmtp 
	(Cipher TLSv1:DES-CBC3-SHA:168) (Exim 3.35 #1 (Debian))
	id 1BF1DY-0004ov-00
	for <testlist@lists.malcolmhardie.com>; Sun, 18 Apr 2004 02:35:32 +0100
(...)

**Comment by Cinek1812** [comment]
And it would be great if you write some tests to this class :)

**Comment by dzefrej0** [comment]
Oh i see, Okay, no problem.

**Comment by dzefrej0** [comment]
Listen up team :) where I have to do these tests? On what branch?

**Comment by dzefrej0** [comment]
Okay found.

**Pull request merged**
